[Definition]
actionstart = python3 /opt/yachtplus/state_action.py start
actionstop = python3 /opt/yachtplus/state_action.py stop
actioncheck = python3 /opt/yachtplus/state_action.py check
actionban = python3 /opt/yachtplus/state_action.py ban <ip> <bantime> <time>
actionunban = python3 /opt/yachtplus/state_action.py unban <ip>
